name: Run tests

# триггер
on: [ push, workflow_dispatch ]

jobs: #  аналог этапов
  run-tests:
    name: Set up services (review apps) and run tests
    runs-on: ubuntu-latest
    steps: # шаги конкретной job
      - name: Checkout repository # копируем файлы репозитория внутрь CI агента
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cash Maven repository
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Services
        run: bash infra/docker_compose/restart_docker.sh

      - name: Run tests
        run: ./mvnw clean test